### ISSUE TITLE
Add support for open-meteo backend

### ISSUE THREAD

**Issue by jkuester** [LibreWeather/libre-weather-api#11]
https://github.com/open-meteo/open-meteo offers free weather forecast APIs for open-source developers and non-commercial use and seems well aligned with the goals of LibreWeather.  We should support consuming data from open-meteo as an alternative to OWM.  

Seems best to make this configurable at the time of deployment.

**Comment by TobiTenno** [comment]
so are you thinking something like an environment variable?

**Comment by jkuester** [comment]
Yeah, something like that.  (Seems like we probably don't need a full yml config yet...)

**Comment by TobiTenno** [comment]
still could make one, if that's the direction we wanna go with. yml config is just as valid as environment vars
